name: CI/CD

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: Build
      run: |
        yarn
        yarn build

    # Deploy either preview or production
    - name: Deploy
      uses: nwtgck/actions-netlify@v1.1.0
      with:
        publish-dir: './dist'
        production-branch: 'master'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: 'Deployed via ${{ github.workflow }} workflow'
        enable-pull-request-comment: true
        enable-commit-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
