name: CI/CD

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Necessary to grab the HEAD commit from the source branch when
        # acting on a PR. Otherwise, `git log` will only contain the merge commit
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Create Deploy Message
      run: |
        # Grab the branch path from the appropriate (PR vs. push) property on context
        FULL_PATH_REF="${{ github.event.pull_request.head.ref || github.ref }}"
        # Strip "refs/heads/" from the start
        REF=${FULL_PATH_REF#refs\/heads\/}
        # Get the short form of the SHA
        SHA=$(git rev-parse --short ${{ github.event.pull_request.head.sha || github.sha }})
        # Set it in env
        echo "::set-env name=SHA::$SHA"
        # Yank the commit message from the log, using the SHA
        COMMIT_MSG=$(git log -n 1 --format=%s $SHA)
        # Set it in env
        echo "::set-env name=COMMIT_MSG::$COMMIT_MSG"
        # If it's a PR, use the title, otherwise, use the commit message
        MSG="${{ github.event.pull_request.title || env.COMMIT_MSG }}"
        # Create the deploy message
        DEPLOY_MESSAGE="$REF@$SHA: $MSG (${{ github.workflow }} workflow)"
        # Set it in env
        echo "::set-env name=DEPLOY_MESSAGE::$DEPLOY_MESSAGE"

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Build
      run: |
        yarn install --pure-lockfile --non-interactive
        yarn build

    # Deploy either preview or production
    - name: Deploy
      uses: nwtgck/actions-netlify@v1
      with:
        publish-dir: './dist'
        production-branch: 'master'
        alias: deploy-preview-${{ env.SHA }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: ${{ env.DEPLOY_MESSAGE }}
        enable-pull-request-comment: true
        enable-commit-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
