name: CI/CD

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Necessary to grab the HEAD commit from the source branch
        # Otherwise, the SHA in github.context.* points to the merge commit
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Debug
      run: |
        echo "GitHub context: ${{ toJson(github) }}"

    # - name: Create Deploy Message
    #   run: |
    #     # Grab the branch path from the appropriate (PR vs. push) property on context
    #     FULL_PATH_REF="${{ github.head_ref || github.ref }}"
    #     # Strip "refs/heads/" from the start
    #     REF=${FULL_PATH_REF#refs\/heads\/}
    #     # Yank the commit message from the log, using the SHA
    #     COMMIT_MSG=$(git log -n 1 --format=%s ${{ github.event.after }})
    #     # Get the short form of the SHA
    #     SHA=$(git rev-parse --short ${{ github.event.after }})
    #     # Create the deploy message
    #     MESSAGE="$REF@$SHA: $COMMIT_MSG (${{ github.workflow }} workflow)"
    #     # Set it in env
    #     echo "::set-env name=DEPLOY_MESSAGE::$MESSAGE"
      
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: Build
      run: |
        yarn install --pure-lockfile --silent
        yarn build

    # Deploy either preview or production
    - name: Deploy
      uses: nwtgck/actions-netlify@v1.1.0
      with:
        publish-dir: './dist'
        production-branch: 'master'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: ${{ env.DEPLOY_MESSAGE }}
        enable-pull-request-comment: true
        enable-commit-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
