name: CI/CD

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Get Commit Message
      run: |
        SHA_AND_MSG=$(git log --oneline -n 1 ${{ github.event.after }})
        echo "::set-env name=COMMIT_SHA_AND_MSG::$SHA_AND_MSG"
      
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: Build
      run: |
        yarn
        yarn build

    # Deploy either preview or production
    - name: Deploy
      uses: nwtgck/actions-netlify@v1.1.0
      with:
        publish-dir: './dist'
        production-branch: 'master'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: '${{ github.head_ref }}@${{ env.COMMIT_SHA_AND_MSG }} (${{ github.workflow }} workflow)'
        enable-pull-request-comment: true
        enable-commit-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
